#
# Makefile for pclake-gotm-lake setup.
#

name	= gotm-2m
setup	= $(name)

include Rules.make

$(name)_clean:

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
