#
# Makefile for 'gotm-lake-20m' setup.
#

name	= gotm-lake-20m
setup	= $(name)

include Rules.make

$(name)_clean:

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
